<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite" duration-ms="10" started-at="2017-06-15T08:31:49Z" finished-at="2017-06-15T08:31:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10" started-at="2017-06-15T08:31:49Z" finished-at="2017-06-15T08:31:49Z">
      <class name="com.Nagarro.nagp.selenium.testSuites.TestSuite">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8]" name="setUp" is-config="true" duration-ms="5940" started-at="2017-06-15T14:01:43Z" finished-at="2017-06-15T14:01:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="TC01(java.util.Hashtable)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8]" name="TC01" duration-ms="0" started-at="2017-06-15T14:01:49Z" data-provider="dataProvider" finished-at="2017-06-15T14:01:49Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:110)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1240)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.Nagarro.nagp.selenium.testSuites.TestSuite.commonDataProvider(TestSuite.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:51)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:41)
	... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method name="TC02" signature="TC02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8]" status="SKIP" duration-ms="0" finished-at="2017-06-15T14:01:49Z" started-at="2017-06-15T14:01:49Z" depends-on-methods="com.Nagarro.nagp.selenium.testSuites.TestSuite.TC01" data-provider="dataProvider" description="Test case to create a one way trip for given number of passengers and locations">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSuite.TC02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSuite.TC02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method name="TC03" signature="TC03(java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8]" status="SKIP" duration-ms="0" finished-at="2017-06-15T14:01:49Z" started-at="2017-06-15T14:01:49Z" depends-on-methods="com.Nagarro.nagp.selenium.testSuites.TestSuite.TC02" data-provider="dataProvider" description="Test case to verify user is able to select flights for the trip">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSuite.TC03(java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSuite.TC03(java.lang.String, java.lang.String)[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.Nagarro.nagp.selenium.testSuites.TestSuite@7a1ebcd8]" name="tearDown" is-config="true" duration-ms="1046" started-at="2017-06-15T14:01:49Z" finished-at="2017-06-15T14:01:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Nagarro.nagp.selenium.testSuites.TestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- suite -->
</testng-results>
